name = "RunToSolveJuliaRegistry"
uuid = "407ac96f-52f6-497f-aeca-d16f73898ecd"
repo = "https://github.com/runtosolve/RunToSolveJuliaRegistry"
description = "Julia registry for RunToSolve julia packages"

[packages]
01f7396e-a581-4110-84fa-e8964400bef8 = { name = "AISIS100", path = "A/AISIS100" }
74a74c3a-221d-4cd1-a4eb-c3c8149e7592 = { name = "LinesCurvesNodes", path = "L/LinesCurvesNodes" }
82b4978f-06ae-48e0-88e8-a26b4f7a0fa1 = { name = "CUFSM", path = "C/CUFSM" }
82fbcf34-b322-4c20-ba17-babb40f2cc8c = { name = "CUFSMModalGeometry", path = "C/CUFSMModalGeometry" }
e5713cf4-1a83-4860-95bf-b82253e75fb4 = { name = "CrossSectionGeometry", path = "C/CrossSectionGeometry" }
